### ISSUE TITLE
VX_RPP - OPENCL Backend Failure

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1210]
Develop branch is failing OpenCL backend with #1197 merge. Add the fix to develop to merge to master @LakshmiKumar23 

```
/var/jenkins_home/workspace/_Short-GPUOpen_MIVisionX_PR-1207/b19TE91IH/OpenCL/mivisionx/amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp:48:9: error: use of undeclared identifier 'return_status'
        return_status = VX_ERROR_NOT_IMPLEMENTED;
        ^
1 error generated when compiling for gfx90a.

```

**Comment by kiritigowda** [comment]
Fixed with TOT master.
